project:
  type: website

website:
  title: "Lynn Kuhlwein"
  navbar:
    left:
      - personal.qmd
      - studies.qmd
      - Assignment3.qmd
      - href: LynnKuhlweinCV.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

